### PR TITLE
Update to electrs v0.9.4

### PR DESCRIPTION
**Pull request by prusnak**

### CODE REVIEW

**Comment by tlindi** [comment]
Nice would solve My issue too: https://github.com/getumbrel/umbrel/issues/1046#issuecomment-1003788529

**Comment by lukechilds** [comment]
Thanks @prusnak and thanks @tlindi for the bug report!

**Comment by tlindi** [comment]
Electrs verbose / login is changed in 0.9.4 and it now requires --log-filters. See:  https://github.com/romanz/electrs/blob/master/src/config.rs lines 291-294

My slow machines are still building so I have not tested this PR. Yesterday I noticed electrs 0.9.4 container don't start for me without logging parameter set. 

(now building latest)

**Comment by tlindi** [comment]
Okay tested with merged. Needs a small change:

docker logs electrs gives:
Error: please use `log_filters` to set logging verbosity

But after changing: umbrel/templates/electrs-sample.toml 

-verbose = 2
+log_filters = "INFO"

(and running scripts/configure)

my electrs is now happily running :)

**Comment by prusnak** [comment]
> Okay tested with merged. Needs a small change:

@tlindi will you please open an issue in https://github.com/getumbrel/umbrel repo?

**Comment by tlindi** [comment]
> > Okay tested with merged. Needs a small change:
> 
> @tlindi will you please open an issue in https://github.com/getumbrel/umbrel repo?

Done: https://github.com/getumbrel/umbrel/issues/1183

**Pull request merged**
